; *****************************************
; * Source Engine                         *
; *---------------------------------------*
; * Date : 2020.01.28                     *
; * Last Update : 2020.02.05              *
; * Version : 0.3                         *
; * File : Stack System for Source Engine *
; * Author : Frederic Cordier             *
; *****************************************
; This file contain all the MACROS that can be used from the PARSER to port
; an existing language to the Source Engine format.
; Help : http://www.pjhutchison.org/emulation/AmigaAsmTutorial.txt

; When the parser will send arguments to a Source Engine method, it will have to use MACROS
; to cast these arguments to the arguments stack.
; For example, a simple AMOS Command like : PEN 5
; Will be decomposed in 2 lines :
; PushIntegerToStack 5
; CallMethod sePen
;
; It's a simple example as more complex ones will require more calculation.
; For example : Screen Open 0, WIDTH, HEIGHT + 50, 256, Lowres + Laced
; Will produce a more complex result :
; PushConstantToStack Laced
; PushConstantToStack Lowres
; AddStackIntegers                             ResultInStack = Laced + Lowres
; PushIntegerToStack 256
; PushIntegerToStack 50
; PushGlobalVariableToStack HEIGHT
; AddStackIntegers                             ResultInStack = 50 + Height
; PushGlobalVariableToStack WIDTH
; PushIntegerToStack 0
; CallMethod seOpenScreen                      Stack will contain 5 arguments : 0, WIDTH, result of HEIGHT + 50, 256, result of Lowres + Laced
;
; When the source code will be compiled, the MACRO compiler will transform the MACRO in Assembler code.
; The case of Floating point and String is a bit more complex. Because both are casted as static String
; in a <<FLOATNUMBERLABEL: dc.b "floatingNumber",0>> or <<STRINGLABEL: dc.b "ZeString",0>>
; The label must be generated by the parser using for example a string label + increment number.
; Example for floating number : FTNL001 : <<dc.b "floatingNumber",0>> where 001 will auto increment each
; time a new floating number will be added as static value.
; Same for String. The problem is that Floating number must be converted from string to FFP number as there
; is no direct way to insert them directly as floating number in the Assembler source code.
;
; -------------------------------------------------------------
;  Here is the list of all the PARSER MACRO that can be used :
; -------------------------------------------------------------
; PushStaticIntegerToStack IntegerValue
; PushStaticFloatToStack   FloatValueStringRepresentationLabel
; PushStaticStringToStack  StringLabel
;
PushStaticIntegerToStack       MACRO
	Move.l	#\1,(a4)+
                               ENDM

PushStaticStringToStack        MACRO
	Move.l	\1,(a4)+
                               ENDM

PushStaticFloatToStack         MACRO
	Move.l	\1,a0