program <- ( line NEWLINE )+ line

line <- statement
      / statement COLON statement
      /

statement <- assignment
           / screen_open

assignment <- identifier EQUAL expression

screen_open <- SCREEN_OPEN expression COMMA expression COMMA expression COMMA expression COMMA expression



constant <- [0-9]+
          / 'Lowres'
          / 'Laced'

expression <- product ( PLUS product / MINUS product )*

product <- monadic ( STAR power / SLASH power )*

power <- monadic ( POWER monadic )*

monadic <- MINUS? value

value <- OPEN_PAR expression CLOSE_PAR
       / identifier
       / constant

identifier <- ident_start ident_cont*
ident_start <- [a-zA-Z_]
ident_cont <- ident_start / [0-9]

SCREEN_OPEN <- 'Screen Open '

COLON <- ':'
COMMA <- ','
NEWLINE <- '\n'
SPACE <- ' '
PLUS <- '+'
MINUS <- '-'
STAR <- '*'
SLASH <- '/'
OPEN_PAR <- '('
CLOSE_PAR <- ')'
EQUAL <- '='
POWER <- '^'
