
; *****************************************
; * Source Engine                         *
; *---------------------------------------*
; * Date : 2021.05.27                     *
; * Last Update : 2020.05.27              *
; * Version : 0.1                         *
; * File : game Engine for Source Engine  *
; * Author : Frederic Cordier             *
; *****************************************
; This file contains configuration equates for the Source Engine.
; This file can be generated by the Parser or IDE that will be used for Source Engine development.
debugMode              equ 1

; ****************************************************
; seVariablesBuffer = The size of the buffer to store global and locals variables.
seVariablesBuffer      equ 4096*6              ; 4096*6 bytes Allocation = 4096 variables (each uses 6 bytes)

; ****************************************************
; seMaxProceduresCalls = The maximum amount of consecutives procedures calls (from inside procedures) before casting an error
; If you increase the value larger than 256, you should also increase the seVariablesBuffer as recursive calls allocates procedures variables again on each call.
seMaxProceduresCalls   equ 256                 ; If procedure call procedure call procedure, limit 256 consecutives calls

; ****************************************************
; seMaxGosubCalls = The maximum amount of consecutives 'gosub' calls before casting an error.
; This value condition a pointer buffer to store gosub return 
seMaxGosubCalls        equ 256                 ; if Gosub call Gosub, limit to 256 consecutives calls


; ****************************************************
; seMaxGosubCalls = The maximum amount of imbricated For/Next loops datas
; This value condition a pointer buffer to store For/Next loops datas 
seMaxLoops             equ 16                  ; Maximum of imbricated For/Next loops
LoopsBufferSize        equ 16                  

; ****************************************************
; seCopperMode = The mode used for graphic drawing (0=AmigaOS graphics/intuitions, 1=AmosStyle)
seCopperMode           equ 0

; ****************************************************
DepthBufferSize     equ     16                 ; Set the maximum of TempVariables that can be pushed in Stack (must allocate memory buffer)
seMaxScreens        equ     16                 ; We currently handle a maximum of 16 screens
StackBufferSize     equ     256

; ****************************************************
fullErrorMessages   equ     1                  ; if Set to 1, then include full error messages. Otherwise just include ErrorID
